### ISSUE TITLE
Verify message deleted after few seconds

### ISSUE THREAD

**Issue by ghost** [InceptionTime/GuildedRobloxVerification#1]
Hey there! We recently added the bot to our guilded server and while it has been extremely useful, one issue I've noticed is that the private replies the bot messages are deleted after a few seconds which can be annoying for the user experience as the user has to keep typing !verify. Is there a way this could be fixed so the message stays around, is there a reason its like this or is this something on guilded's end?

Thanks!

**Comment by InceptionTime** [comment]
I can look into this for sure, I thought I only enabled this on Roblox official servers.

(ETA for me to push a fix for this will be this weekend 18th-20th of Nov)

**Comment by InceptionTime** [comment]
So I have increase the time the message is displayed to the user from 10 seconds to 30. This is a thing so that the bot self cleans the verify channel.

The bot deletes the users !verify message so it only makes sense to delete the bots message or else it's just going to be filled with spam.

If this still doesn't work for you, reply back and I can look into separating this flow from Roblox official servers vs non Roblox official servers.

**Comment by ghost** [comment]
Just curious as to what you mean by spam? The bot privately replies, so it shouldn't fill the channel with spam for other users, just for yourself which isn't to big of an issue?

If you could separate it that would be great, thanks!

**Comment by InceptionTime** [comment]
For our Roblox Creators server using the moderator view our verify channel was filled with these messages 
![image](https://user-images.githubusercontent.com/17829184/203185497-398a7b14-515c-40be-a86a-f8f9d330a15c.png)

You're totally right it's private responses but I wanted it to be consistent as after verifying it would delete the users message.

I can totally look into separating the two flows next weekend

**Comment by ghost** [comment]
Ahhh got it! Perhaps making this a setting that server owners could set would be a possibility? If not, all good 👍

**Comment by InceptionTime** [comment]
I believe this should be fixed now but I haven't properly tested it. Let me know if you are still seeing the bots messages delete itself

**Comment by ghost** [comment]
Works, thank you very much!
