### ISSUE TITLE
Verification

### ISSUE THREAD

**Issue by georgeroyle2011** [InceptionTime/GuildedRobloxVerification#5]
Every time I say verify I just get ignored, I do have a red X next to my name but I don’t know what that means

**Comment by InceptionTime** [comment]
@georgeroyle2011 What is your Guilded & Roblox username and ID?

**Comment by kocimateo** [comment]
!version

**Comment by PremiumMustafa341123** [comment]
!verify

**Comment by PremiumMustafa341123** [comment]
!version

**Comment by InceptionTime** [comment]
Did not follow up with username and userID, cannot replicate issue.
