### ISSUE TITLE
Verification sets name properly but does not apply role reliably. 

### ISSUE THREAD

**Issue by PolarisWasInDenial** [InceptionTime/GuildedRobloxVerification#6]
**Describe the bug**
The Roblox-Guilded verification handler bot properly sets a user's username to match their linked Roblox account in the verified Roblox Creators discord server. 

**To Reproduce**
1. Create a Guilded account.
2. Link a Roblox account 
3. Join the Guilded Server
4. Run the `!verify` command 
5. See error occur.

**Expected behavior**
The bot, upon verifying a user's Roblox account, should rename the user *and* give them the `verified` role.

**Screenshots**
![Screenshot_20240719_020706_Guilded.png](https://github.com/user-attachments/assets/d910bd60-38af-49b9-924a-de9837d9e555)

**Guilded Server ID:**
`WloZrvQR`
**Additional context**
This is *especially* odd considering that it functioned properly within the Roblox-Programs server previously when I was first invited to it, where I am a member of the Community Feedback Program. I am unsure if the two are connected, but feel it important to mention them here.

**Comment by InceptionTime** [comment]
Hey! This is a Guilded API issue, I'm going to keep bugging them about these issues

**Comment by PolarisWasInDenial** [comment]
@InceptionTime In an effort to spare DevRel from being spam pinged by everyone experiencing this bug, I went ahead and put [a message](https://www.guilded.gg/roblox-creators/groups/G3p5YNoD/channels/705fab53-5603-4773-8773-4f02a3d0d861/chat?messageId=38c5de2e-3070-4907-980c-99bdf6999bf0) in the server's Verification channel to _try_ to direct users here for status updates - hopefully it works.

**Comment by Kokihsusg** [comment]
@InceptionTime 👋hi

**Comment by InceptionTime** [comment]
@PolarisWasInDenial, this might actually be fixed now - could you please confirm?

**Comment by PolarisWasInDenial** [comment]
@InceptionTime Appears fixed in both Roblox Creators (`WloZrvQR`) and Roblox Creator Events (`1EDAXAWj`) as of 2 minutes ago from the time of writing.
